//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSet
    {
        public int AyarOgrenID { get; set; }
        public string OgrenSifre { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
