//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int OgrenciID { get; set; }
        public string OgrenciAdı { get; set; }
        public string OgrenciSoyadı { get; set; }
        public string OgrenciNo { get; set; }
        public string OgrenciTC { get; set; }
        public string OgrenciSınıf { get; set; }
        public string OgrenciDogumT { get; set; }
        public string OgrenciCinsiyet { get; set; }
        public string OgrenciAdres { get; set; }
        public string OgrenciFoto { get; set; }
        public Nullable<int> OgrenciVeliID { get; set; }
    
        public virtual Veliler Veliler { get; set; }
    }
}
