//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int OgretmenID { get; set; }
        public string OgretmenAdı { get; set; }
        public string OgretmenSoyadı { get; set; }
        public string OgretmenTC { get; set; }
        public string OgretmenTelNo { get; set; }
        public string OgretmenMail { get; set; }
        public string OgretmenIL { get; set; }
        public string OgretmenIlce { get; set; }
        public string OgretmenAdres { get; set; }
        public string OgretmenBrans { get; set; }
        public string OgretmenFoto { get; set; }
    }
}
